# @package _global_

# specify here default training configuration
defaults:
  - model: vocals
  - logger:
    - wandb
    - tensorboard
  - paths: default.yaml
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

hydra:
  run:
    dir: ${get_eval_log_dir:${ckpt_path}}

#ckpt_path: "G:\\Experiments\\KLRef\\vocals.onnx"
ckpt_path: ${oc.env:ckpt_path}

split: 'test'
batch_size: 4
device: 'cuda:0'
bss: fast
single: False # for debug investigation
overlap_factor:

##data_dir: ${oc.env:data_dir}
eval_dir: ${oc.env:data_dir}
wandb_api_key: ${oc.env:wandb_api_key}
extended_dataset: ${oc.env:extended_dataset}
save_separated: False

logger: []

pool_workers: 8
double_chunk: False
#extra_lst: ["guitar_processed", "horn_processed", "siren_processed", "upfilters_processed", "vocalchops_processed"]
#pos_lst: []

